# Generated by Django 3.2.18 on 2023-03-03 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('archive', models.BooleanField(default=False)),
                ('votes', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_posts', to=settings.AUTH_USER_MODEL)),
                ('modifed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
