# Generated by Django 3.2.18 on 2023-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
