# Generated by Django 3.2.18 on 2023-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_question_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basepost',
            old_name='modifed_by',
            new_name='modified_by',
        ),
    ]
