# Generated by Django 3.2.18 on 2023-03-05 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_rename_modifed_by_basepost_modified_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-votes']},
        ),
    ]
