# Generated by Django 3.2.18 on 2023-03-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20230307_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basepost',
            name='_body_rendered',
        ),
        migrations.RemoveField(
            model_name='basepost',
            name='body_markup_type',
        ),
        migrations.AlterField(
            model_name='basepost',
            name='body',
            field=models.TextField(),
        ),
    ]
