# Generated by Django 3.2.18 on 2023-03-07 03:03

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20230307_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepost',
            name='_body_rendered',
            field=models.TextField(default='**TEXT** __TEXT2__', editable=False),
        ),
        migrations.AddField(
            model_name='basepost',
            name='body_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('markdown', 'markdown')], default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basepost',
            name='body',
            field=markupfield.fields.MarkupField(default='**TEXT** __TEXT2__', rendered_field=True),
        ),
    ]
