# Generated by Django 3.2.18 on 2023-03-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20230307_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='body_markup_type',
            field=models.CharField(choices=[('', '--'), ('markdown', 'markdown')], default='markdown', max_length=30),
        ),
    ]
