# Generated by Django 3.2.18 on 2023-03-07 03:08

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_basepost_body_markup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='_body_rendered',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='basepost',
            name='body',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
