# Generated by Django 3.2.18 on 2023-03-08 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0014_basepost_vote_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='vote_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
