# Generated by Django 3.2.18 on 2023-03-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_profile_score'),
        ('forum', '0017_alter_basepost_vote_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepost',
            name='vote_users',
            field=models.ManyToManyField(to='home.Profile'),
        ),
    ]
