# Generated by Django 3.2.18 on 2023-03-08 16:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_alter_basepost_vote_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=('created_on',)),
        ),
    ]
