# Generated by Django 3.2.18 on 2023-03-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_alter_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
