# Generated by Django 3.2.18 on 2023-03-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20230309_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
