# Generated by Django 3.2.18 on 2023-03-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0004_alter_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
